### ISSUE TITLE
Bind neighborhood data to leaflet map

### ISSUE THREAD

**Issue by gabrielesh** [hackoregon/housing-frontend#17]
After #16 merges, we'll have all the API stuff in place to connect real data to the component library components. The most important one to do is the map, since it's the single piece towards our MVP. Here's the detailed design map, based on the most recent wireframes: https://docs.google.com/document/d/13auCFoXqkYfVYTxkUEwczL4ghrmeqxkA5cVHYp9pack/edit?usp=sharing

**Comment by DingoEatingFuzz** [comment]
Assigned to @nmuldavin

**Comment by nmuldavin** [comment]
Should close, addressed by #22
