### ISSUE TITLE
Use pretty components in place of the dropdowns we are currently using

### ISSUE THREAD

**Issue by DingoEatingFuzz** [hackoregon/housing-frontend#18]
The Component Library has fancy dropdowns and bells and whistles that we should use in place of the generic HTML `<select>`s that we have in place now.

**Comment by nmuldavin** [comment]
Issue I noticed with this: for whatever reason the leaflet map pane defaults to a z-index of 400. This is hiding the dropdowns when they overlap with the map. I'm sure there is a way to change the z-index ordering in leaflet but it might be easier to just set the z-index of the select menu to something higher than 400.
<img width="1414" alt="screen shot 2017-04-30 at 9 52 29 am" src="https://cloud.githubusercontent.com/assets/6165476/25566354/d7024cd8-2d8b-11e7-8974-8300ebb61271.png">
