### ISSUE TITLE
Write site copy

### ISSUE THREAD

**Issue by DingoEatingFuzz** [hackoregon/housing-frontend#19]
@gabrielesh has been working away on this and will deliver it to us by 11am this Saturday (April 29th).

**Comment by DingoEatingFuzz** [comment]
Please post the copy here when it's ready!

**Comment by tyreer** [comment]
Happy to give a close read and offer feedback if needed. Just let me know what time window is right if you'd like my eyes on it.

**Comment by gabrielesh** [comment]
Thank you so much @tyreer ! Here's the link to the website copy draft that I'm working on. https://docs.google.com/document/d/1TECaOtrq4sHdapN0LdjM72vUZWapSCUh7aIcRETeUQ0/edit?usp=sharing I welcome edits from any and all!

**Comment by tyreer** [comment]
Looking great @gabrielesh! Added a few comments there. Cheers! Miss y'all
