### ISSUE TITLE
Create line charts for production vs cost from static jsons

### ISSUE THREAD

**Issue by gabrielesh** [hackoregon/housing-frontend#24]
@JohnTasto is creating line charts using the guidance and jsons in this link https://docs.google.com/document/d/13auCFoXqkYfVYTxkUEwczL4ghrmeqxkA5cVHYp9pack/edit?usp=sharing
Since they are small, the jsons will load with the code rather than being pulled from the back end

**Comment by JohnTasto** [comment]
Done #40
