### ISSUE TITLE
Pull in Voter Registration Gifs and copy

### ISSUE THREAD

**Issue by gabrielesh** [hackoregon/housing-frontend#32]
The UI relationship of the Voter Registration Data to the rest of the Housing project is outlined here: https://docs.google.com/document/d/13auCFoXqkYfVYTxkUEwczL4ghrmeqxkA5cVHYp9pack/edit?usp=sharing
The final copy for the Voter Registration Data sequence is available at https://docs.google.com/document/d/1MmiLOn-yZQ_GghLUeQEtY6sAXzWQjQeCR02cfJQlop8/edit?usp=sharing 
Higher quality gifs and css styling (if desired) is posted below.

**Comment by gabrielesh** [comment]
[WebSiteArchive.zip](https://github.com/hackoregon/housing-frontend/files/966408/WebSiteArchive.zip)
[Plots.zip](https://github.com/hackoregon/housing-frontend/files/966409/Plots.zip)
Here's the original assets

**Comment by gabrielesh** [comment]
Many thanks John for taking this on! If for some reason it doesn't work, Christopher Moravec, who created this, will just update his website and we can link to it at http://www.apps.moraveclabs.com/hack-oregon-voter/ (but beware--as of now this has old copy, so don’t take the and graphs from here!).

**Comment by JohnTasto** [comment]
This is going to make a very tall website... I'll try playing around with the router after I get off work tonight but no promises.

**Comment by nmuldavin** [comment]
Merged #43
