### ISSUE TITLE
Create an api adapter

### ISSUE THREAD

**Issue by DingoEatingFuzz** [hackoregon/housing-frontend#9]
This will be a simple layer that encapsulates all the URL building and data fetching we will have to do. This way anyone interested in changing UI will already have a collection of actions to dispatch to get data.

Here is the current spec of the API. I'm not sure if we will end up using all the possible query params, but it's simple enough to support them all.

**API Spec:**

  - `GET /housing_api/affordable/`
    - demographic _(string, finite set, FK)_
    - housing_size _(string, finite set, FK)_
  - `GET /housing_api/rent/`
    - rent_amt _(number)_
    - housing_size _(string, finite set, FK)_
    - rent_amt_gt _(number)_
    - rent_amt_lt _(number)_

This API spec is also always subject to change. A good adapter should be easily extended.

The goal is to have this done by the Saturday buildathon!

**Comment by nmuldavin** [comment]
Does your work here involve setting up the redux store to accept the data, or just the getting part? I'm starting to think about / work on getting the store set up, just wanted to see where you're at.

**Comment by DingoEatingFuzz** [comment]
This will be both: an interface to the api via async redux actions.
